### ISSUE TITLE
DataLoadCoordinator loads elements for CUBA schema in Jmix screens

### ISSUE THREAD

**Issue by Flaurite** [Haulmont/jmix-cuba#117]
### Description
See forum: [topic](https://forum.jmix.io/t/extended-browse-screens-are-not-loaded-automatically-test-project-included/838).

### Steps to reproduce

1. Download demo project: [unfetchedattribute2.zip](https://github.com/Haulmont/jmix-cuba/files/7709361/unfetchedattribute2.zip)
2. Open: _Application -> Companies_

**ER**
3 records should be shown

**AR**
Nothing is shown

**Comment by klaus7** [comment]
See https://github.com/Haulmont/jmix-cuba/blob/6f94847bde6d4f15f6fee4e477ad588cf01144ad/cuba/src/main/java/com/haulmont/cuba/web/gui/facets/CubaDataLoadCoordinatorFacetProvider.java#L57
compared to io.jmix.ui.facet.DataLoadCoordinatorFacetProvider#loadRefresh where the data is retrieved from the elements, as specified in the XSD, not the attributes as in the CubaDataLoadCoordinatorFacetProvider

**Comment by reznikova21** [comment]
1.2.0-SNAPSHOT - verified
