### ISSUE TITLE
Unable to clear 'User' field for scheduled task on migrated project

### ISSUE THREAD

**Issue by artemy63** [Haulmont/jmix-cuba#124]
Test case:

1. Create a new Cuba project
2. Add some bean with an interface
3. Migrate the created project to Jmix
4. Run migrated project
5. Go to 'Scheduled Tasks' menu and create a new scheduled task based on bean created on step#2
6. Set to 'User' field some value, e.g. "admin", save task
7. Try to edit configured task and clear 'User' field

AR: Field is not cleared

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.2.0-SNAPSHOT
Jmix Studio plugin version: 1.2.SNAPSHOT4049-213
IntelliJ version: IntelliJ IDEA 2021.3 (Ultimate Edition)
