### ISSUE TITLE
Add to module.properties jmix.securityImplementation with "standard" value

### ISSUE THREAD

**Issue by Flaurite** [Haulmont/jmix-cuba#22]
### Description
CUBA has "jmix-security" dependencies and login screens (AppLoginWindow, LoginScreen) use its API.
`LoginScreen` has "login" id so it always is registered as the default login screen.

If a simple application with a compatibility module does not have `jmix.securityImplementation=standard` it won't start because `LoginScreen` uses beans that are only provided by `jmix.securityImplementation=standard`.

Add `jmix.securityImplementation = standard` to _module.properties_.
Check tests in CUBA and dependent modules.

**Comment by knstvk** [comment]
It's not needed after Haulmont/jmix-core#31.
