### ISSUE TITLE
Allow enter comma-separated values for generic filter IN condition

### ISSUE THREAD

**Issue by Flaurite** [Haulmont/jmix-cuba#33]
### Description
- Subsystem: Generic Filter
- Migrate fix from: [cuba-platform/cuba#1643](https://github.com/cuba-platform/cuba/issues/1643)
- Waiting for `ListEditorDelegate` and `WebListEditor` migration

**Comment by GlebDurygin** [comment]
Fixed in Haulmont/jmix-cuba#2
