### ISSUE TITLE
Config properties stored in DB - management UI

### ISSUE THREAD

**Issue by knstvk** [Haulmont/jmix-cuba#4]
See `com.haulmont.cuba.gui.app.core.appproperties.AppPropertiesBrowse` and around.

**Comment by artemglinov** [comment]
### QA Notes

1. Create a new Jmix project with `implementation 'io.jmix.cuba:jmix-cuba-starter'`
dependency (in `build.gradle` file).
2. Follow the instructions in [https://doc.cuba-platform.com/manual-7.2/config_interface_usage.html](https://doc.cuba-platform.com/manual-7.2/config_interface_usage.html). Note that all test methods corresponding to some properties must have `@Source(type = SourceType.DATABASE)` annotation (or just annotate the created configuration interface the same way).
3. Run the app and go to **Administration** > **Application Properties** screen. Check whether all the screen elements reproduce the behaviour and state of the corresponding UI in CUBA projects.
