### ISSUE TITLE
Fix cuba generic filter

### ISSUE THREAD

**Issue by GlebDurygin** [Haulmont/jmix-cuba#43]
See comments from Haulmont/jmix-cuba#31

### QA
1) 1 and 4 cases from the comments will be fixed in: [Haulmont/jmix-cuba#55](https://github.com/Haulmont/jmix-cuba/issues/55)
2) 3 case. Define `folderActionsEnabled="true"` in the `<filter>` element.
3) 6 case. LookupField won't be shown due to the mechanism of entity statistics is absent and we cannot check which component should be created.

**Comment by maistrenkoIulia** [comment]
TC: screen with legacy filer>add search conditions>set value
pin applied
remove condition
remove pin
ER:
![image](https://user-images.githubusercontent.com/66992566/118108038-92b83200-b3f0-11eb-8402-0a3803609178.png)

AR:
![image](https://user-images.githubusercontent.com/66992566/118108066-99df4000-b3f0-11eb-84c1-b158d253a956.png)

**Comment by maistrenkoIulia** [comment]
from https://github.com/Haulmont/jmix-cuba/issues/31
2 - ok
3 - ok
5 - NOK ('available for all users' resets before commit and close screen)
![image](https://user-images.githubusercontent.com/66992566/118108815-7e286980-b3f1-11eb-9cda-599be012b81a.png)
