### ISSUE TITLE
Support for injecting Logger into Spring beans

### ISSUE THREAD

**Issue by knstvk** [Haulmont/jmix-cuba#57]
CUBA had ability to inject Logger to beans:
```
@Inject
private Logger logger;
```

Make sure it works for migrated projects having jmix-cuba in dependencies.

See also haulmont/jmix-ui#474.

**Comment by bulgakovea** [comment]
For QA:
1) Open project without `cuba-starter` dependency
2) Create Spring Bean
3) Try to Inject org.slf4j.Logger into Spring Bean

**Comment by owlet1997** [comment]
Case 1: 
couldn't get expected result

If bean has 'Logger' injecting exception occurs during building project 

![image](https://user-images.githubusercontent.com/45730069/121185473-29a0ce80-c877-11eb-8d56-972e0c1595f4.png)

If controller has 'Logger' injecting exception occurs during runtime

![image](https://user-images.githubusercontent.com/45730069/121185506-30c7dc80-c877-11eb-8948-7e8327361620.png)
