### ISSUE TITLE
Generic filter should check for EntityComboBox name while generating entity lookup field

### ISSUE THREAD

**Issue by Flaurite** [Haulmont/jmix-cuba#58]
### Description
The main problem occurs in the `Param` and `PersistenceManagerClient` classes.

In the `Param` we checked which component should be used for an entity: LookupPickerField or PickerFIeld. `PersistenceManagerClient` uses `jmix.ui.component.entityFieldType` property and checked for `LookupPickerField` name. If we set `EntityComboBox`, filter will use PickerField.

### QA
Download attached project: [demo.zip](https://github.com/Haulmont/jmix-cuba/files/6560176/demo.zip)

1.  Add `jmix.ui.component.entityFieldType.Order_=entityComboBox` to the properties file and launch the app.
2. Open CUBA v7 screens -> "Seven Order Line browse"
3. Add "Search condition to the filter
4. Select "Order"

Component with dropdown list should be generated.

**Comment by maistrenkoIulia** [comment]
verified
