### ISSUE TITLE
@Lookup field annotation should be taken into account in bulkEdit action

### ISSUE THREAD

**Issue by Flaurite** [Haulmont/jmix-cuba#63]
### Description
Port fix from: https://github.com/cuba-platform/cuba/issues/3139

### QA
1. Add CUBA starter: `implementation 'io.jmix.cuba:jmix-cuba-starter'`
2. Create two entities with one-to-many association between them
3. Create legacy screens
4. Add `<bulkEditor for="my_table_id"/>` to the browser screen of entity that has property for another.
5. Add annotation `@Lookup(type = LookupType.DROPDOWN)` on entity property, e.g.:
```
    @Lookup(type = LookupType.DROPDOWN)
    @JoinColumn(name = "ORDER_ID")
    @ManyToOne(fetch = FetchType.LAZY)
    private Order order;
```
6. Launch the app and open screen that contains `bulkEditor`
7. Edit some entity via `bulkEditor`
8. The `EntityComboBox` should be created without actions.

Another cases: 
- add annotation with actions: `@Lookup(type = LookupType.DROPDOWN, actions = {"clear"})`. Should be created `EntityComboBox` with clear action.
- add annotation with `@Lookup(type = LookupType.SCREEN, actions = {"clear"})`. Should be created `EntityPicker` with clear action.

**Comment by DartVerder** [comment]
- with `@Lookup(type = LookupType.DROPDOWN)`

**ER:** The EntityComboBox should be created without actions.
**AR:** Created combo box + picker field with clear action
![image](https://user-images.githubusercontent.com/69783839/124617688-30c3f800-de88-11eb-8fbb-b05622887c0b.png)

- with `@Lookup(type = LookupType.SCREEN, actions = {"clear"})`

**ER:** Should be created EntityPicker with clear action.
**AR:** No picker field, unable to edit
![image](https://user-images.githubusercontent.com/69783839/124616824-7633f580-de87-11eb-8f20-3ae4440aec58.png)

**Comment by Flaurite** [comment]
1) Fixed;
2) Now `Lookup` action is always added to the PickerField regardless `@Lookup` annotation's actions.
    If annotation does not contain actions for `LookupType.SCREEN` - `Lookup` and `Clear` actions will be added.
