### ISSUE TITLE
PickerField Lookup and Open actions do not work

### ISSUE THREAD

**Issue by Flaurite** [Haulmont/jmix-cuba#66]
### Description
Implement TODOs.

#### Steps to reproduce
1. Download attached project: [demo.zip](https://github.com/Haulmont/jmix-cuba/files/7136007/demo.zip)

2. Go to _CUBA v6 screens -> Six OrderLine Browse_
3. Edit some entity
4. In the editor try to use "lookup" and "open" actions in the PickerField. They should open screens.

**Comment by reznikova21** [comment]
1.1.0-SNAPSHOT - verified
