### ISSUE TITLE
Scheduled tasks

### ISSUE THREAD

**Issue by knstvk** [Haulmont/jmix-cuba#7]
The current plan is to move this functionality into a compatibility module and employ a third-party library for new projects.

- [x] Move entities
- [x] Move required services
- [x] Move screens
- [x] Check screen 'Scheduled tasks browse'
- [x] Check screen 'Scheduled tasks edit'
- [x] Check screen 'Execution history'
- [x] Check screen 'Running tasks'
- [x] Check scheduled execution
- [x] Write tests

**Comment by natfirst** [comment]
For QA: see CUBA doc https://doc.cuba-platform.com/manual-7.2/scheduled_tasks.html
