### ISSUE TITLE
RowsCount wraps its components even if there is available space (port to 1.0)

### ISSUE THREAD

**Issue by Flaurite** [Haulmont/jmix-cuba#77]
See original https://github.com/Haulmont/jmix-cuba/issues/76

### Description
1. Create legacy lookup screen for some entity
2. Add `<rowsCount/>` element to the table/dataGrid
3. Open this screen.

**ER**
![image](https://user-images.githubusercontent.com/22093943/130962064-1016788c-8ed2-42b9-9f57-e66d2d1f12a9.png)

**AR**
![image](https://user-images.githubusercontent.com/22093943/130962143-df2fdd6c-9254-4ea9-be75-aef304e818bc.png)

**Comment by lovtsovaik** [comment]
verified for halo, hover, helium themes
